site_name: X14S
site_author: X14S s.c.s.
site_description: Fieldhockey coaching as well as video and performance analysis

copyright: >
  Copyright &copy; 2015 - 2023 X14S s.c.s. –
  <a href="#__consent">Change cookie settings</a>

theme:
  name: material
  favicon: images/favicon.ico
  icon:
    logo: fontawesome/solid/circle
  features:
    - navigation.expand
    - navigation.indexes
    - navigation.instant
    - navigation.sections
    - navigation.top
    - navigation.tracking
    - toc.follow
  font:
    text: IBM Plex Sans
    code: IBM Plex Mono
  palette:
    primary: black
    accent: blue

extra_css:
  - css/extra.css

extra:
  analytics:
    provider: google
    property: G-L60C5W79LH
  consent:
    title: Cookie consent
    description: >- 
      We use cookies to recognize your repeated visits and preferences, as well
      as to measure the effectiveness of our documentation and whether users
      find what they're searching for. With your consent, you're helping us to
      make our documentation better.
    actions:
      - accept
      - reject
  social:
    - icon: fontawesome/brands/twitter 
      link: https://twitter.com/x14santo
    - icon: fontawesome/brands/instagram
      link: https://instagram.com/x14santo
    - icon: fontawesome/brands/wikipedia-w
      link: https://fr.wikipedia.org/wiki/Xavier_Santolaria

markdown_extensions:
  - attr_list
  - md_in_html
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg

plugins:
  - search
  - awesome-pages:
      filename: .pages
      collapse_single_pages: false
      strict: false
  - glightbox